### ISSUE TITLE
Issue with apogee_data path

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#1]
My computer is formatting the path in a weird way
Running 
`ap.download('2M15141711+0044474', type='aspcap')`

Returns the following error 
FileNotFoundError: [Errno 2] No such file or directory: '/Users/caganze/Research/apogee_all/apogee_data/:/allStar-l30e.2.fits'

The colon (:) between my path and  the file shouldn't be there

**Comment by caganze** [comment]
export APOGEE_DATA="/Users/caganze/Research/apogee_all/apogee_data/:${APOGEE_DATA}"

**Comment by jbirky** [comment]
export APOGEE_DATA=/Users/path_to/apogee_data
