### ISSUE TITLE
plotModel

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#10]
`ap.plotModel(data1)`

/Users/caganze/Research/apogee_all/apogee_tools/apogee_tools/spec_tools.py in load_flux(self, parameters)
     95         '''
     96         print(parameters)
---> 97         key = self.key_name.format(*parameters)
     98         with h5py.File(self.filename, "r") as hdf5:
     99             try:

TypeError: iteration over a 0-d array

**Comment by jbirky** [comment]
Removed this function from spec_tools.py
