### ISSUE TITLE
optimizeVSINI

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#11]
`ap.optimizeVSINI(data1,mdl)`

same issue as optimizeRV,
/Users/caganze/Research/apogee_all/apogee_tools/apogee_tools/spec_tools.py in optimizeVSINI(spec, mspec, **kwargs)
    684     mask = np.where((m_wave > xrange[0]) & (m_wave < xrange[1]))
    685     m_wave, m_flux = m_wave[mask], m_flux[mask]
--> 686     mspec = Spectrum(wave=m_wave, flux=m_flux, params=params)
    687 
    688     chi_vals = {}

NameError: name 'Spectrum' is not defined

 I think 
`from .core import* `
might fix this

**Comment by jbirky** [comment]
Removed this function from spec_tools.py
