### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#12]
`import apogee_tools as ap`

----> 1 import apogee_tools as ap

/Users/caganze/Research/apogee_all/apogee_tools/apogee_tools/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function, unicode_literals
      2 
----> 3 from .core import *
      4 from .spec_tools import *
      5 from .lsf import *

/Users/caganze/Research/apogee_all/apogee_tools/apogee_tools/core.py in <module>()
     18 
     19 from apogee_tools.spec_tools import _rvShift
---> 20 from libraries import features
     21 
     22 #Get the path of apogee_tools file

ImportError: cannot import name 'features'
I just updated the module, i get this error, perhaps you could from .features import* ? Thanks

**Comment by jbirky** [comment]
ok, I have moved this file and changed the import, so I think it should be working now
