### ISSUE TITLE
'BASE' is not defined in the 'getModel' function

### ISSUE THREAD

**Issue by chihchunhsu** [jbirky/apogee_tools#16]
mdl = ap.getModel(params=[3200, 5.0, 0.0], grid='PHOENIX', xrange=[15200,16940])
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-6d294ceb66be> in <module>()
----> 1 mdl = ap.getModel(params=[3200, 5.0, 0.0], grid='PHOENIX', xrange=[15200,16940])

/Users/dinohsu/projects/apogee_all/apogee_tools/apogee_tools/utils/read.py in getModel(**kwargs)
    228 
    229     grid     = kwargs.get('grid', 'BTSETTLb')
--> 230     grid_lib = BASE + '/libraries/' + grid + '_APOGEE.hdf5'
    231 
    232     params   = kwargs.get('params', [3000, 5.0, 0.0])

NameError: name 'BASE' is not defined

**Comment by jbirky** [comment]
fixed in commit 558499e
