### ISSUE TITLE
Problem importing apogee_tools

### ISSUE THREAD

**Issue by ElizabethMorh** [jbirky/apogee_tools#20]
input: import apogee_tools as ap

Output:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Elizabeth/python/apogee_tools/apogee_tools/__init__.py", line 5, in <module>
    from .cannon_tools.run_cannon import labelToSpec, loadLabels, initializeTrainingSet, runCannon, crossValidate
  File "/Users/Elizabeth/python/apogee_tools/apogee_tools/cannon_tools/run_cannon.py", line 360
    nlabels = len(labels)

**Comment by jbirky** [comment]
I pushed some changes (rewrote labelToSpect, added a function, and removed syntax errors) for run_cannon.py, and it works now for me. Can you try it again?

**Comment by ElizabethMorh** [comment]
I tried, but now it says:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a55d514def34> in <module>()
----> 1 import apogee_tools as ap

/Users/Elizabeth/python/apogee_tools/apogee_tools/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function, unicode_literals
      2 
----> 3 from .core import Spectrum
      4 
      5 from .cannon_tools.run_cannon import labelToSpec, loadLabels, initializeTrainingSet, synthesizeFlux, runCannon, crossValidate

ModuleNotFoundError: No module named 'apogee_tools.core'

**Comment by jbirky** [comment]
Hm, I am not sure... It is working on my computer, and I've pushed all of my files. Did you pull the code after I posted the last message?

**Comment by ElizabethMorh** [comment]
Now it's working! I did pull the code again and now it's solved.

Thank you!

**Comment by jbirky** [comment]
Ok good!
