### ISSUE TITLE
error on search.py

### ISSUE THREAD

**Issue by aburgasser** [jbirky/apogee_tools#21]
Commands:

params = ['TEFF']
ranges = [[0,3600]]
source_table = ap.multiParamSearch(par=params, select=ranges, save_dir='/Users/adam/Desktop/tmp.csv',model='MARCS')

Error:

<ipython-input-14-5aab3a600d00> in <module>()
      1 params = ['TEFF']
      2 ranges = [[0,3600]]
----> 3 source_table = ap.multiParamSearch(par=params, select=ranges, save_dir='/Users/adam/Desktop/tmp.csv',model='MARCS')

/Users/adam/python_codes/apogee_tools/apogee_tools/utils/search.py in multiParamSearch(**kwargs)
    324     # Save data frame to csv file and save to the 'output' directory specified by keyword argument
    325     tmin, tmax = select[0][0], select[0][1]
--> 326     lmin, lmax = select[1][0], select[1][1]
    327     mmin, mmax = select[2][0], select[2][1]
    328 

IndexError: list index out of range

**Comment by jbirky** [comment]
Fixed in commit `3d70fc9`
