### ISSUE TITLE
Download issue 

### ISSUE THREAD

**Issue by ElizabethMorh** [jbirky/apogee_tools#7]
ap.download('2M15141711+0044474', type='apStar')
and 
ap.download('2M15141711+0044474', type='aspcap')

returns
TypeError: buffer is too small for requested array

but  ap.download('2M15141711+0044474', type='apVisit') works fine downloading the files.

**Comment by ElizabethMorh** [comment]
Now I got this error overtime I want to download using:
ap.download('2M03290406+3117075-0', type='apStar')

Returns:
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jbirky** [comment]
Downloading format in documentation is up to date
