### ISSUE TITLE
wget 

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#8]
For some users, there seems to be a certificate issue

`wget https://data.sdss.org/sas/dr13/apogee/spectro/redux/r6/allVisit-l30e.2.fits`

I get a certificate error 
ERROR: cannot verify data.sdss.org's certificate, issued by ‘CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O=GoDaddy.com\\, Inc.,L=Scottsdale,ST=Arizona,C=US’:
  Self-signed certificate encountered.
To connect to data.sdss.org insecurely, use `--no-check-certificate'.

to resolve this I need to run 
`wget https://data.sdss.org/sas/dr13/apogee/spectro/redux/r6/allVisit-l30e.2.fits --no-check-certificate`

You could make this option the default for downloading using wget

**Comment by caganze** [comment]
or in the readme you can make everyone  alias wget='wget --no-check-certificate'

**Comment by jbirky** [comment]
adding this to the next push

**Comment by jbirky** [comment]
added this to the readme
