### ISSUE TITLE
optimizeRV

### ISSUE THREAD

**Issue by caganze** [jbirky/apogee_tools#9]
`ap.optimizeRV(data, mdl)`
has an error
/Users/caganze/Research/apogee_all/apogee_tools/apogee_tools/spec_tools.py in optimizeRV(sp1, sp2, **kwargs
 612     #Turn cross-correlated spectrum into spectrum object
--> 613     cc_sp1 = Spectrum(wave=shift_wave, flux=flux1, sigmas=sp1.sigmas, name=sp1.name)
    614 
    615     return rv, cc_sp1, sp2

NameError: name 'Spectrum' is not defined

I think you need to import Spectrum from core.py
i think you could just use 
`from .core import*` in spec_tools.py ?

**Comment by jbirky** [comment]
Removed this function from spec_tools.py
